export const AUTH_ROUTE = '/auth'
export const MAIN_ROUTE = '/'
export const REG_ROUTE = '/reg'
export const SEARCH_ROUTE = '/search'
export const PROFILE_ROUTE = '/profile'
export const REGUSER_ROUTE = '/regfinal'